
spring:
  application:
    name: demo-consumer

 # Configure a port for your service
server.port: 9910

middleware:
  service-directory-base-url: https://mobility-middleware.de/test/service-directory/api
  consumer.api.enabled: true
